### PR TITLE
ubuntu 24 flist fix

### PR DESCRIPTION
**Pull request by PeterNashaat**

### CODE REVIEW

**Review by hossnys — APPROVED** [review]

**Comment by xmonader** [comment]
Why is that not merged till now? @PeterNashaat @hossnys

**Comment by PeterNashaat** [comment]
- we tracked it down to issue in zos on mainnet and devnet, https://github.com/threefoldtech/zos/issues/2420 
- issue fixed in devnet but not mainnet  
- @xmonader should i wait to verify issue is fixed in mainnet as well to merge ?

**Comment by scottyeager** [comment]
This is just symlinking `vmlinuz` to an empty file. See #308 and #309 for a correct fix. Suggest to close this PR.

**Comment by PeterNashaat** [comment]
Created that PR with the wrong branch will close it without merging and continue discussion over there.

**Pull request closed without merging**
